{{- if .Values.bffServer.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    description: bff-ingress
    displayName: bff-ingress
    httpSend: /
    ingress-lb: {{ .Values.ingress.name }}
    kubernetes.io/ingress.class: {{ .Values.ingress.name }}
    nginx.ingress.kubernetes.io/enable-access-log: "false"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "false"
    nginx.ingress.kubernetes.io/load-balance: round_robin
    nginx.ingress.kubernetes.io/proxy-body-size: ""
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/server-alias: ""
    nginx.ingress.kubernetes.io/upstream-vhost: $host
    nginx.ingress.kubernetes.io/proxy-buffering: "on"  # Important!
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_cache static-cache;
      proxy_cache_valid 404 10m;
      proxy_cache_use_stale error timeout updating http_404 http_500 http_502 http_503 http_504;
      proxy_cache_bypass $http_x_purge;
      add_header X-Cache-Status $upstream_cache_status; # check X-Cache-Status to see if it's HIT
  labels:
    ingress-lb: {{ .Values.ingress.name }}
  name: bff-server-ingress
  namespace: {{ .Release.Namespace }}
spec:
#  ingressClassName: {{ .Values.ingress.name }}
  {{- if .Values.deploymentConfig.bffHttpsEnabled }}
  tls:
    - hosts:
        - {{ .Values.bffServer.host }}
      secretName: oidc-server-root-secret
  {{- end }}
  rules:
  - host: {{ .Values.bffServer.host }}
    http:
      paths:
      - backend:
          service:
            name: bff-server
            port:
              number: 8022
        path: /
        pathType: ImplementationSpecific
{{- end }}
