# Default values for cluster-component.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Overwrite ingress-nginx chart template
ingress-nginx:
  # MUST update this value
  deployedHost: &deployedHost
    <replaced-ingress-node-name>
  controller:
    ingressClassResource:
      name: portal-ingress
    ingressClass: portal-ingress
    image:
      repository: hub.tenxcloud.com/u4a-component/ingress-nginx-controller
      tag: v1.3.0
    admissionWebhooks:
      enabled: false
      patch:
        enabled: true
        image:
          registry: hub.tenxcloud.com
          image: u4a-component/kube-webhook-certgen
          digest: ""
    updateStrategy:
      type: Recreate
    extraArgs:
      update-status:
      report-node-internal-ip-address:
      http-port: 8080
      https-port: 8443
      enable-ssl-passthrough: true
      ssl-passthrough-proxy-port: 16443
    service:
      enabled: false
      type: ClusterIP
      internal:
        enabled: true
    config:
      use-gzip: "true"
      enable-vts-status: "true"
      large-client-header-buffers: 4 1m
      max-worker-connections: "65535"
      vts-default-filter-key: $server_name
      worker-processes: "4"
      http-snippet: |
        proxy_cache_path /tmp/bff-cache levels=1:2 keys_zone=static-cache:2m max_size=100m inactive=7d use_temp_path=off;
        proxy_cache_key $scheme$proxy_host$request_uri;
        proxy_cache_lock on;
        proxy_cache_use_stale updating;
    nodeSelector:
      kubernetes.io/os: linux
      # MUST update this value
      kubernetes.io/hostname: *deployedHost

cert-manager:
  enabled: true
  # Required: Cert manager for certificate management
  image: hub.tenxcloud.com/u4a-component/cert-manager-controller:v1.8.0
  caInjectorImage: hub.tenxcloud.com/u4a-component/cert-manager-cainjector:v1.8.0
  webhookImage: hub.tenxcloud.com/u4a-component/cert-manager-webhook:v1.8.0

openebs:
  enabled: false
  localprovisioner:
    image: hub.tenxcloud.com/u4a-component/provisioner-localpv
    basePath: /var/openebs/local
    hostpathClass:
      enabled: true
      name: openebs-localpv
      isDefaultClass: false
  ndm:
    image: hub.tenxcloud.com/u4a-component/node-disk-manager
  ndmOperator:
    image: hub.tenxcloud.com/u4a-component/node-disk-operator
  helper:
    image: hub.tenxcloud.com/u4a-component/linux-utils

metallb:
  enabled: false
  # Must configure the available addresses if metallb is enabled
  ipAddresses:
  - 192.168.1.10-192.168.90.15
  controller:
    image:
      repository: hub.tenxcloud.com/u4a-component/controller
      tag: v0.13.4
  speaker:
    image:
      repository: hub.tenxcloud.com/u4a-component/speaker
      tag: v0.13.4
  # disabled by default
  frr:
    image:
      repository: hub.tenxcloud.com/u4a-component/frr
      tag: v8.3.0
